#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require 'optparse'

options = {
  :app_name   => "gitbot",
  :backtrace  => true,
  :dir        => "/home/fdammeke/gitrepo/gitbot",
  :dir_mode    => :normal,
#  :ontop      => true,
  #:mode       => "exec",
#  :multiple   => true,
#  :log_dir    => "/tmp/",
  :log_output => true,
}

OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename $0} -a [ACTION] -c [CONFIG]"
  opts.on("-a", "--action ACTION", "Action: start | stop | status") do |action|
    options[:action] = action
  end
  opts.on("-c", "--config CONFIG", "Yaml config file") do |config|
    options[:config] = config
    options[:ARGV] = [options[:action], '--', config] || "config.yml"
  end
end.parse!

pwd = Dir.pwd
Daemons.run_proc('gitbot.rb',options) do
  Dir.chdir(pwd)
  exec "ruby bin/gitbot.rb #{options[:config]}"
end
